# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - apis/userprofile/**

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: apis/userprofile

    strategy:
      matrix:
        node-version: [8.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run build steps defined in package.json
      run: npm run build --if-present
    - name: Run unit tests
      run: npm test
    - name: Run code coverage
      run: npm run cover
    - name: Publish code coverage with Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create an issue if failed
      id: create-issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        assignees: aaronchong888
        filename: .github/AUTO_ISSUE_TEMPLATE.md